//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.12 at 07:12:54 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hibernate.org/xsd/hibernate-mapping", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kepler.hibernate3;
