//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.12 at 07:12:54 PM CST 
//


package kepler.hibernate3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.hibernate.org/xsd/hibernate-mapping}return-scalar"/>
 *         &lt;element ref="{http://www.hibernate.org/xsd/hibernate-mapping}return"/>
 *         &lt;element ref="{http://www.hibernate.org/xsd/hibernate-mapping}return-join"/>
 *         &lt;element ref="{http://www.hibernate.org/xsd/hibernate-mapping}load-collection"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.hibernate.org/xsd/hibernate-mapping}attlist.resultset"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "returnScalarOrReturnOrReturnJoin"
})
@XmlRootElement(name = "resultset")
public class Resultset {

    @XmlElements({
        @XmlElement(name = "return", type = Return.class),
        @XmlElement(name = "return-join", type = ReturnJoin.class),
        @XmlElement(name = "load-collection", type = LoadCollection.class),
        @XmlElement(name = "return-scalar", type = ReturnScalar.class)
    })
    protected List<Object> returnScalarOrReturnOrReturnJoin;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the returnScalarOrReturnOrReturnJoin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnScalarOrReturnOrReturnJoin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnScalarOrReturnOrReturnJoin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Return }
     * {@link ReturnJoin }
     * {@link LoadCollection }
     * {@link ReturnScalar }
     * 
     * 
     */
    public List<Object> getReturnScalarOrReturnOrReturnJoin() {
        if (returnScalarOrReturnOrReturnJoin == null) {
            returnScalarOrReturnOrReturnJoin = new ArrayList<Object>();
        }
        return this.returnScalarOrReturnOrReturnJoin;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
